import { StyleSheet } from 'react-native';

export const estilos = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#E8ECEF',
    padding: 20,
  },
  headerContainer: {
    alignItems: 'center',
    marginTop: 10,
    marginBottom: 20,
  },
  titulo: {
    fontSize: 32,
    fontWeight: '900',
    color: '#1A365D',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 3,
    borderLeftWidth: 6,
    borderLeftColor: '#38A169',
  },
  subtitulo: {
    fontSize: 20,
    color: '#2D3748',
    fontWeight: 'bold',
    marginBottom: 15,
  },
  texto: {
    fontSize: 16,
    color: '#4A5568',
    lineHeight: 24,
    marginBottom: 8,
  },

  imagemBanner: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    marginBottom: 15,
    resizeMode: 'contain', 
  },
  
  linhaSwitch: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#EDF2F7',
  },
  input: {
    backgroundColor: '#F7FAFC',
    borderWidth: 1,
    borderColor: '#CBD5E0',
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    marginBottom: 15,
    color: '#2D3748',
  },
  jogoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F7FAFC',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
  },
  time: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2D3748',
    width: '40%',
    textAlign: 'center',
  },
  versus: {
    fontSize: 14,
    fontWeight: '900',
    color: '#E53E3E',
    backgroundColor: '#FED7D7',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    overflow: 'hidden',
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    backgroundColor: '#1A365D',
    paddingVertical: 12,
    paddingHorizontal: 15,
    marginTop: 15,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    textAlign: 'center',
    letterSpacing: 2,
  },
  linhaTabela: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  posicaoTabela: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#718096',
    width: 35,
  },
  nomeTabela: {
    fontSize: 16,
    color: '#2D3748',
    fontWeight: '600',
    flex: 1, 
  },
  pontosTabela: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#38A169', 
  },
  footerTabela: {
    backgroundColor: '#FFFFFF',
    height: 15,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  }
});